version : "3.0"

services :
    quasar :
        depends_on:
            - bisar
        build: ./quasar/
        restart: always
        ports: 
            - "8000:8000"
        networks:
            my-network:
                aliases:
                    - api.bisar.local
    bisar:
        build: ./bisar_core/
        networks:
            - my-network

networks:
    my-network: {}
